# Generated by Django 3.0.2 on 2020-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("survey", "0010_survey_editable_answers")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="expire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Validity"),
        ),
        migrations.AddField(model_name="survey", name="publish_date", field=models.DateField(auto_now=True)),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="The choices field is only used if the question \
                type\nif the question type is 'radio', 'select', or\n'select multiple' \
                    provide a comma-separated list of\noptions for this question .",
                null=True,
                verbose_name="Choices",
            ),
        ),
    ]
