# Generated by Django 3.0.2 on 2020-02-24 22:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("survey", "0011_auto_20200210_1928")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .",
                null=True,
                verbose_name="Choices",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="expire_date",
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 2), verbose_name="Expiration date"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Users can see it and answer it"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="publish_date",
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 24), verbose_name="Publication date"),
        ),
    ]
